<table>
<tr>
<td>Category</td>
<td>Name</td>
<td>Description</td>
<td>Examples</td>
</tr>
<tr>
<td>None</td>
<td>None</td>
<td>The null object</td>
<td></td>
</tr> 
<tr>
<td>Numeric</td>
<td>int</td>
<td>Integar</td>
<td>1</td>

</tr>
<td></td>
<td>float</td>
<td>Floating point number</td>
<td>345.554</td>

</tr>
<td></td>
<td>bool</td>
<td>Boolean</td>
<td>True/False</td>

</tr>
<td></td>
<td>complex</td>
<td>Complex Numbers</td>
<td>1 + 2j</td>

</tr>
<td>Sequences</td>
<td>str</td>
<td>String</td>
<td>"Hello World!"</td>

</tr>
<td></td>
<td>list</td>
<td>List of arbitarty objects</td>
<td>[1,"hello",3.14, True]</td>
</tr>
<tr>

</tr>
<td></td>
<td>Tuple</td>
<td>Group of arbitrary objects</td>
<td>("Milk",5)</td>
</tr>

</tr>
<td></td>
<td>range</td>
<td>Creates a range of integers</td>
<td>range(0,5)</td>
</tr>

</tr>
<td>Mapping</td>
<td>dict</td>
<td>Dictionairy of Key-Values pairs</td>
<td>{1: "Hello"}</td>

<td></td>
<td>set</td>
<td>Mutable, unordered collection of items</td>
<td>{1,2,3}</td>
</tr>
</table>

<table>
<tr>
<td>Category</td>
<td>Name</td>
<td>Description</td>
<td>Examples</td>
</tr>
<tr>
<td>None</td>
<td>None</td>
<td>The null object</td>
<td></td>
</tr> 
<tr>
<td>Numeric</td>
<td>int</td>
<td>Integar</td>
<td>1</td>

</tr>
<td></td>
<td>float</td>
<td>Floating point number</td>
<td>345.554</td>

</tr>
<td></td>
<td>bool</td>
<td>Boolean</td>
<td>True/False</td>

</tr>
<td></td>
<td>complex</td>
<td>Complex Numbers</td>
<td>1 + 2j</td>

</tr>
<td>Sequences</td>
<td>str</td>
<td>String</td>
<td>"Hello World!"</td>

</tr>
<td></td>
<td>list</td>
<td>List of arbitarty objects</td>
<td>[1,"hello",3.14, True]</td>
</tr>
<tr>

</tr>
<td></td>
<td>Tuple</td>
<td>Group of arbitrary objects</td>
<td>("Milk",5)</td>
</tr>

</tr>
<td></td>
<td>range</td>
<td>Creates a range of integers</td>
<td>range(0,5)</td>
</tr>

</tr>
<td>Mapping</td>
<td>dict</td>
<td>Dictionairy of Key-Values pairs</td>
<td>{1: "Hello"}</td>

<td></td>
<td>set</td>
<td>Mutable, unordered collection of items</td>
<td>{1,2,3}</td>
</tr>
</table>