In [3]:
# evaluate prophet time series forecasting model on hold out dataset
import pandas as pd
from prophet import Prophet
from sklearn.metrics import mean_absolute_error
from matplotlib import pyplot

In [4]:
#load data
df = pd.read_csv('/Users/gagandeepkundi/data-engineering/projects/weather-etl-ml-project/src/airflow/dags/data/02_intermediate/weather.csv')

df = df.drop(columns='region').sort_values('last_updated')

df.tail()

,name,country,lat,lon,tz_id,localtime_epoch,localtime,last_updated_epoch,last_updated,temp_c,...,precip_in,humidity,cloud,feelslike_c,feelslike_f,vis_km,vis_miles,uv,gust_mph,gust_kph
46,Warsaw,Poland,52.25,21.0,Europe/Warsaw,1670150703,2022-12-04 11:45,1670149800,2022-12-04 11:30,0.0,...,0.0,100,100,-5.1,22.9,2.6,1.0,1.0,15.0,24.1
47,Warsaw,Poland,52.25,21.0,Europe/Warsaw,1670151918,2022-12-04 12:05,1670151600,2022-12-04 12:00,0.0,...,0.0,100,100,-5.2,22.7,2.7,1.0,2.0,15.2,24.5
48,Warsaw,Poland,52.25,21.0,Europe/Warsaw,1670155124,2022-12-04 12:58,1670154300,2022-12-04 12:45,1.0,...,0.0,93,100,-3.9,25.0,2.6,1.0,2.0,15.2,24.5
49,Warsaw,Poland,52.25,21.0,Europe/Warsaw,1670155499,2022-12-04 13:04,1670155200,2022-12-04 13:00,1.0,...,0.0,93,100,-4.0,24.8,2.6,1.0,2.0,15.9,25.6
50,Warsaw,Poland,52.25,21.0,Europe/Warsaw,1670156102,2022-12-04 13:15,1670155200,2022-12-04 13:00,1.0,...,0.0,93,100,-4.0,24.8,2.6,1.0,2.0,15.9,25.6